version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  spark:
    image: bitnami/spark
    ports:
      - "8080:8080"
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
      SPARK_SSL_ENABLED: "no"
    depends_on:
      - kafka
      - zookeeper

  monappli:
    build: .
    depends_on:
      - spark
      - kafka
      - zookeeper
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      ZOOKEEPER: "zookeeper:2181"
    # Plus d'options d'environnement si nécessaire
